clc;
clear all;
close all;
x1 = input("Enter the first sequence x1(n):");
L = length(x1);
N = 2*L-1;
yn = xcorr(x1,x1);
disp("The values of y(n) are =");
disp(yn);
n1 = 0:L-1;
subplot(2,1,1);
stem(n1,x1);
grid on;
xlabel("n1");
ylabel("Amplitude");
title("Plot of first signal");
n2 = 0:N-1;
subplot(2,1,2);
stem(n2,yn);
grid on;
xlabel("n2");
ylabel("Amplitude");
title("Plot of second signal");