clc;
ap = input("Enter the attenuated pass band:");
as = input("Enter the attenuated stop band:");
Fp = input("Enter the pass band frequency:");
Fs = input("Enter the stop band frequency:");
f = input("Enter the sampling frequency:");
fp = 2*(Fp./f);
fs = 2*(Fs./f);
[n wn] = buttord(fp,fs,ap,as);
[b a] = butter(n,wn,"low");
t = 0:0.1:pi;
[h,omega] = freqz(b,a,t);
m = 20*log10(abs(h));
an = angle(h);
subplot(2,1,1);
plot(omega/pi,m);
grid on;
xlabel("Normalized Frequency");
ylabel("Gain in db");
title("Magnitude Response of low pass iir filter");
subplot(2,1,2);
plot(omega/pi,an);
grid on;
xlabel("Normalized Frequency");
ylabel("Phase in radians");
title("Phase Response of low pass iir filter");